#!/bin/sh

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>


case "$1" in
	configure)
		if ! dpkg-statoverride --list /etc/lfd-bld-reporter >/dev/null 2>&1; then
			dpkg-statoverride --update --quiet --add root root 0700 /etc/lfd-bld-reporter
		fi

		if ! dpkg-statoverride --list /etc/lfd-bld-reporter/config.ini >/dev/null 2>&1; then
			dpkg-statoverride --update --quiet --add root root 0640 /etc/lfd-bld-reporter/config.ini
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
